
language: python
python:
 - 3.6
install: pip install -r requirements.txt -r test-requirements.txt
script:
- flake8 --ignore=E501 --import-order-style=google --application-import-names=main customer/*.py org/*.py
- nosetests -v
